Joesphus problem for recursion added
TechOUs/DSKaKhel pull request #67
Opened 2020-10-04 19:21 UTC by riyavaryani

2020-10-05 18:18 UTC, GauravWalia19 commented
Please create a issue with hacktoberfest20 template

2020-10-05 18:28 UTC, GauravWalia19 requested changes
Update the README also.

2020-10-05 19:13 UTC, riyavaryani commented
changes done

2020-10-10 04:14 UTC, GauravWalia19 commented on ARRAYS/C++/Recursion/josephusProblem.cpp
> +    int n;
Please use good variable names like 
**int n  -> int noOfPeople**

2020-10-10 04:14 UTC, GauravWalia19 commented on ARRAYS/C++/Recursion/josephusProblem.cpp
> +    cin>>k;
int k -> int kthPeopleToKill

2020-10-10 04:15 UTC, GauravWalia19 commented on ARRAYS/C++/Recursion/josephusProblem.cpp
> +{
update the variables for this method also

2021-09-15 19:12 UTC, GauravWalia19 commented
Thanks for choosing our repository for contributing to Hacktober Fest 20
As a part of the new process this Issue is marked as hacktoberfest-expiry & closed
Please check our new updated contribution guidelines [here](https://github.com/TechOUs/DSKaKhel/blob/master/CONTRIBUTING.md)

2021-09-15 19:12 UTC, closed without merging